export const BADGES = [
  // 🟢 Onboarding
  {
    id: 'first_code',
    title: 'First Code Generated',
    description: 'Generated your first code',
    requirement: 'Generate your first code',
    icon: '💻',
    category: 'code',
  },
  {
    id: 'first_visualization',
    title: 'First Visualization',
    description: 'Visualized your first algorithm',
    requirement: 'Visualize one algorithm',
    icon: '📊',
    category: 'visualization',
  },

  // 🔵 Code milestones
  {
    id: 'code_5',
    title: 'Code Novice',
    description: 'Generated 5 codes',
    requirement: 'Generate 5 codes',
    icon: '🧠',
    category: 'code',
  },
  {
    id: 'code_10',
    title: 'Code Explorer',
    description: 'Generated 10 codes',
    requirement: 'Generate 10 codes',
    icon: '🚀',
    category: 'code',
  },
  {
    id: 'code_25',
    title: 'Code Builder',
    description: 'Generated 25 codes',
    requirement: 'Generate 25 codes',
    icon: '🏗️',
    category: 'code',
  },
  {
    id: 'code_50',
    title: 'Code Engineer',
    description: 'Generated 50 codes',
    requirement: 'Generate 50 codes',
    icon: '🛠️',
    category: 'code',
  },
  {
    id: 'code_100',
    title: 'Code Architect',
    description: 'Generated 100 codes',
    requirement: 'Generate 100 codes',
    icon: '🏛️',
    category: 'code',
  },

  // 🟣 Visualization milestones
  {
    id: 'viz_3',
    title: 'Visual Learner',
    description: 'Visualized 3 algorithms',
    requirement: 'Visualize 3 algorithms',
    icon: '👀',
    category: 'visualization',
  },
  {
    id: 'viz_5',
    title: 'Visual Thinker',
    description: 'Visualized 5 algorithms',
    requirement: 'Visualize 5 algorithms',
    icon: '🔍',
    category: 'visualization',
  },
  {
    id: 'viz_10',
    title: 'Algorithm Analyst',
    description: 'Visualized 10 algorithms',
    requirement: 'Visualize 10 algorithms',
    icon: '📐',
    category: 'visualization',
  },
  {
    id: 'viz_25',
    title: 'Algorithm Strategist',
    description: 'Visualized 25 algorithms',
    requirement: 'Visualize 25 algorithms',
    icon: '♟️',
    category: 'visualization',
  },

  // 🟠 Level badges
  {
    id: 'level_2',
    title: 'Level Up!',
    description: 'Reached level 2',
    requirement: 'Reach level 2',
    icon: '⬆️',
    category: 'level',
  },
  {
    id: 'level_5',
    title: 'Rising Coder',
    description: 'Reached level 5',
    requirement: 'Reach level 5',
    icon: '🌱',
    category: 'level',
  },
  {
    id: 'level_10',
    title: 'Advanced Thinker',
    description: 'Reached level 10',
    requirement: 'Reach level 10',
    icon: '🎓',
    category: 'level',
  },
  {
    id: 'level_20',
    title: 'Problem Solver',
    description: 'Reached level 20',
    requirement: 'Reach level 20',
    icon: '🧩',
    category: 'level',
  },

  // 🟡 XP badges
  {
    id: 'xp_500',
    title: 'XP Hunter',
    description: 'Earned 500 XP',
    requirement: 'Earn 500 XP',
    icon: '⚡',
    category: 'xp',
  },
  {
    id: 'xp_1000',
    title: 'XP Grinder',
    description: 'Earned 1000 XP',
    requirement: 'Earn 1000 XP',
    icon: '🔥',
    category: 'xp',
  },
  {
    id: 'xp_5000',
    title: 'XP Master',
    description: 'Earned 5000 XP',
    requirement: 'Earn 5000 XP',
    icon: '💎',
    category: 'xp',
  },
]
