export const queueOperationsMeta = {
  enqueue: {
    name: "Enqueue",
    algorithmName: "Queue Enqueue",
    label: "Enqueue (Add to Back)",
    description: "Add an element to the back (rear) of the queue. FIFO - First In First Out.",
    time: "O(1)",
    space: "O(1)",
    stable: true,
    inPlace: true,
    bestCase: "O(1)",
    averageCase: "O(1)",
    worstCase: "O(1)",
    spaceComplexity: "O(1)",
    stableStr: "Stable - maintains relative order"
  },
  dequeue: {
    name: "Dequeue",
    algorithmName: "Queue Dequeue",
    label: "Dequeue (Remove from Front)",
    description: "Remove and return the element from the front of the queue.",
    time: "O(1)",
    space: "O(1)",
    stable: true,
    inPlace: true,
    bestCase: "O(1)",
    averageCase: "O(1)",
    worstCase: "O(1)",
    spaceComplexity: "O(1)",
    stableStr: "Stable - element removal only"
  },
  peek: {
    name: "Peek",
    algorithmName: "Queue Peek",
    label: "Peek (View Front)",
    description: "View the front element without removing it from the queue.",
    time: "O(1)",
    space: "O(1)",
    stable: true,
    inPlace: true,
    bestCase: "O(1)",
    averageCase: "O(1)",
    worstCase: "O(1)",
    spaceComplexity: "O(1)",
    stableStr: "Stable - read-only operation"
  },
  isEmpty: {
    name: "IsEmpty",
    algorithmName: "Queue IsEmpty",
    label: "Is Empty",
    description: "Check if the queue is empty.",
    time: "O(1)",
    space: "O(1)",
    stable: true,
    inPlace: true,
    bestCase: "O(1)",
    averageCase: "O(1)",
    worstCase: "O(1)",
    spaceComplexity: "O(1)",
    stableStr: "Stable - size comparison"
  },
  size: {
    name: "Size",
    algorithmName: "Queue Size",
    label: "Size",
    description: "Get the total number of elements in the queue.",
    time: "O(1)",
    space: "O(1)",
    stable: true,
    inPlace: true,
    bestCase: "O(1)",
    averageCase: "O(1)",
    worstCase: "O(1)",
    spaceComplexity: "O(1)",
    stableStr: "Stable - size counting"
  }
}
