def get_task_definitions():
    return [
        {
            "id": "first_code",
            "title": "Generate your first code",
            "description": "Turn pseudocode into executable code",
            "route": "/generate-code",
            "category": "onboarding",
            "icon": "code",
            "once": True,
            "priority": 100,
            "condition": lambda u: u["stats"]["codes_generated"] == 0,
        },

        {
            "id": "first_visualization",
            "title": "Visualize an algorithm",
            "description": "Understand algorithms step by step",
            "route": "/visualize-playground",
            "category": "onboarding",
            "icon": "eye",
            "once": True,
            "priority": 90,
            "condition": lambda u: u["stats"]["visualizations"] == 0,
        },

        {
            "id": "first_badge",
            "title": "Earn your first badge",
            "description": "Unlock your first achievement",
            "route": "/badges",
            "category": "onboarding",
            "icon": "badge",
            "once": True,
            "priority": 80,
            "condition": lambda u: u["stats"]["badges"] == 0,
        },
        {
            "id": "daily_streak",
            "title": "Don’t break your streak",
            "description": "Complete one task today",
            "route": "/dashboard",
            "category": "streak",
            "icon": "flame",
            "once": False,
            "priority": 95,
            "condition": lambda u: not u["stats"].get("streak_active_today", False),
        },

        {
            "id": "maintain_3_day_streak",
            "title": "Maintain a 3-day streak",
            "description": "Build consistency over 3 days",
            "route": "/dashboard",
            "category": "streak",
            "icon": "flame",
            "once": True,
            "priority": 85,
            "condition": lambda u: u["stats"]["streak"] < 3,
        },

        {
            "id": "maintain_7_day_streak",
            "title": "Maintain a 7-day streak",
            "description": "Consistency creates mastery",
            "route": "/dashboard",
            "category": "streak",
            "icon": "flame",
            "once": True,
            "priority": 75,
            "condition": lambda u: u["stats"]["streak"] < 7,
        },
        {
            "id": "reach_next_level",
            "title": "Reach the next level",
            "description": "Earn XP to level up",
            "route": "/dashboard",
            "category": "progression",
            "icon": "rocket",
            "once": False,
            "priority": 70,
            "condition": lambda u: u["stats"]["xp"] < u["stats"]["xp_next_level"],
        },

        {
            "id": "generate_5_codes",
            "title": "Generate 5 codes",
            "description": "Practice by generating multiple solutions",
            "route": "/generate-code",
            "category": "progression",
            "icon": "code",
            "once": True,
            "priority": 60,
            "condition": lambda u: u["stats"]["codes_generated"] < 5,
        },

        {
            "id": "visualize_5_algorithms",
            "title": "Visualize 5 algorithms",
            "description": "Deepen understanding with visuals",
            "route": "/visualize-playground",
            "category": "progression",
            "icon": "eye",
            "once": True,
            "priority": 50,
            "condition": lambda u: u["stats"]["visualizations"] < 5,
        },
        {
            "id": "check_leaderboard",
            "title": "Check the leaderboard",
            "description": "See how you rank globally",
            "route": "/leaderboard",
            "category": "exploration",
            "icon": "trophy",
            "once": False,
            "priority": 40,
            "condition": lambda u: True,
        },

        {
            "id": "review_activity",
            "title": "Review your activity history",
            "description": "Track your learning journey",
            "route": "/history",
            "category": "exploration",
            "icon": "history",
            "once": False,
            "priority": 30,
            "condition": lambda u: True,
        },
    ]
