export const bfsPseudo = [
  "BFS(graph, startNode)",
  "  queue ← initialize with startNode",
  "  visited ← set containing startNode",
  "  result ← empty array",
  "  ",
  "  while queue is not empty:",
  "    currentNode ← queue.dequeue()",
  "    result.add(currentNode)",
  "    ",
  "    for each neighbor of currentNode:",
  "      if neighbor not in visited:",
  "        visited.add(neighbor)",
  "        queue.enqueue(neighbor)",
  "  ",
  "  return result"
]

export const dfsPseudo = [
  "DFS(graph, startNode)",
  "  visited ← empty set",
  "  result ← empty array",
  "  ",
  "  DFSHelper(startNode):",
  "    visited.add(startNode)",
  "    result.add(startNode)",
  "    ",
  "    for each neighbor of startNode:",
  "      if neighbor not in visited:",
  "        DFSHelper(neighbor)",
  "    ",
  "    return result"
]

export const detectCyclePseudo = [
  "DetectCycle(graph)",
  "  visited ← empty set",
  "  cycleFound ← false",
  "  ",
  "  for each node in graph:",
  "    if node not in visited:",
  "      if DFSVisit(node, null):",
  "        cycleFound ← true",
  "        break",
  "  ",
  "  DFSVisit(node, parent):",
  "    visited.add(node)",
  "    for each neighbor of node:",
  "      if neighbor not in visited:",
  "        DFSVisit(neighbor, node)",
  "      else if neighbor != parent:",
  "        return true (cycle found)",
  "    return false"
]

export const checkPathPseudo = [
  "CheckPath(graph, start, end)",
  "  visited ← empty set",
  "  ",
  "  return DFSPath(start, end, visited)",
  "  ",
  "  DFSPath(node, end, visited):",
  "    if node == end:",
  "      return true",
  "    ",
  "    visited.add(node)",
  "    for each neighbor of node:",
  "      if neighbor not in visited:",
  "        if DFSPath(neighbor, end, visited):",
  "          return true",
  "    ",
  "    return false"
]

export const dijkstraPseudo = [
  "Dijkstra(graph, startNode)",
  "  distances ← {all: ∞, start: 0}",
  "  previous ← empty map",
  "  unvisited ← all nodes",
  "  ",
  "  while unvisited not empty:",
  "    current ← node with min distance",
  "    unvisited.remove(current)",
  "    ",
  "    for each neighbor in current.neighbors:",
  "      if unvisited.contains(neighbor):",
  "        newDist ← distances[current] + weight",
  "        if newDist < distances[neighbor]:",
  "          distances[neighbor] ← newDist",
  "          previous[neighbor] ← current",
  "  ",
  "  return distances"
]

export const astarPseudo = [
  "A*(graph, start, goal)",
  "  openSet ← {start}",
  "  closedSet ← empty set",
  "  gScore ← {all: ∞, start: 0}",
  "  fScore ← {all: ∞, start: h(start)}",
  "  ",
  "  while openSet not empty:",
  "    current ← node in openSet with lowest fScore",
  "    if current == goal:",
  "      return reconstruct_path()",
  "    ",
  "    openSet.remove(current)",
  "    closedSet.add(current)",
  "    ",
  "    for each neighbor of current:",
  "      if neighbor in closedSet:",
  "        continue",
  "      ",
  "      tentativeG ← gScore[current] + weight",
  "      if neighbor not in openSet:",
  "        openSet.add(neighbor)",
  "      else if tentativeG >= gScore[neighbor]:",
  "        continue",
  "      ",
  "      gScore[neighbor] ← tentativeG",
  "      fScore[neighbor] ← tentativeG + h(neighbor)",
  "      previous[neighbor] ← current",
  "  ",
  "  return failure (no path found)"
]

export const primPseudo = [
  "PRIM_MST(graph, startNode)",
  "  key ← {all nodes: ∞}",
  "  parent ← {all nodes: null}",
  "  inMST ← empty set",
  "  key[startNode] ← 0",
  "  ",
  "  while not all nodes in MST:",
  "    u ← node not in MST with minimum key",
  "    inMST.add(u)",
  "    if parent[u] ≠ null:",
  "      add edge (parent[u], u) to MST",
  "    ",
  "    for each neighbor v of u:",
  "      if v not in MST and weight(u,v) < key[v]:",
  "        key[v] ← weight(u, v)",
  "        parent[v] ← u",
  "  ",
  "  return MST edges and total cost"
]

export const kruskalPseudo = [
  "KRUSKAL_MST(graph)",
  "  sortedEdges ← sort all edges by weight",
  "  mst ← empty set",
  "  uf ← UnionFind(all nodes)",
  "  ",
  "  for each edge (u, v, w) in sortedEdges:",
  "    if uf.find(u) ≠ uf.find(v):",
  "      mst.add(edge)",
  "      uf.union(u, v)",
  "    else:",
  "      skip (would create cycle)",
  "  ",
  "  return mst and total cost"
]
