export const deletePseudo = [
  "PROCEDURE DELETE(value)",
  "  IF tree is empty THEN",
  "    RETURN Not Found",
  "  END IF",
  "",
  "  queue ← [root]",
  "  WHILE queue not empty DO",
  "    node ← dequeue()",
  "    IF node.left.value = value THEN",
  "      node.left ← NULL",
  "      RETURN Success",
  "    END IF",
  "    IF node.right.value = value THEN",
  "      node.right ← NULL",
  "      RETURN Success",
  "    END IF",
  "    IF node.left exists THEN",
  "      enqueue(node.left)",
  "    END IF",
  "    IF node.right exists THEN",
  "      enqueue(node.right)",
  "    END IF",
  "  END WHILE",
  "  RETURN Not Found",
  "END PROCEDURE"
]
